### ISSUE TITLE
Use local fonts and icons

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken-explorer-ui#128]
Use local fonts and icons to reduce network time comsuming.

**Comment by Keith-CY** [comment]
@qiweiii Could you take over this optimization?

**Comment by qiweiii** [comment]
@Keith-CY sure

**Comment by qiweiii** [comment]
@Keith-CY  Do you mean using user's local font if it exists OR put fonts in publid of the website

**Comment by Keith-CY** [comment]
> @Keith-CY Do you mean using user's local font if it exists OR put fonts in publid of the website

Put fonts in the public directory so users don't have to fetch them from google's cdn.
