### ISSUE TITLE
 Fonts outside the transaction list do not need to be bolded.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/godwoken-explorer-ui#477]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/25676576/185529472-5ff88b2f-da3b-41c3-9bc9-da5cec69c453.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/25676576/185529614-f53ff5e2-c313-4f54-b301-36635df7f5f2.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/25676576/185529773-ba5c6839-2b74-4f8b-8109-f1d907e91b25.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/25676576/185529878-d44568ef-0bb2-4d1f-b308-afbfc12eb469.png">

Now, outside the transaction list on the page, it is found that there are many fonts that appear bold and need to be adjusted. The number (symbol) before the decimal point of the value in the transaction list needs to be bolded, and other places are not processed.

**Comment by Kirl70** [comment]
I don't think it is necessary to bold numbers outside the list and differentiate the color of numbers after the decimal point, because having too many different styles in the same place can make it look messy.

4 different digital styles in this area alone.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/106060898/185531769-d753dab1-2e91-4a71-b0cc-5cddf1dbb928.png">

**Comment by Keith-CY** [comment]
> I don't think it is necessary to bold numbers outside the list and differentiate the color of numbers after the decimal point, because having too many different styles in the same place can make it look messy.
> 
> 4 different digital styles in this area alone.
> 
> <img alt="image" width="1207" src="https://user-images.githubusercontent.com/106060898/185531769-d753dab1-2e91-4a71-b0cc-5cddf1dbb928.png">

Got it, will be updated in today or tomorrow

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/500

**Comment by FrederLu** [comment]
Verified.
