### ISSUE TITLE
Chore(deps): update dependency wagmi to v0.9.2

### ISSUE THREAD

**Issue by JeffreyMa597** [Magickbase/godwoken-explorer-ui#785]
**Describe the bug**
We need to solve these problems before upgrade `wagmi` to v0.9.2.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/22511289/207390777-d2787231-d1c8-4381-8b3a-fc0ead921fdd.png">

**Comment by Keith-CY** [comment]
`wagmi` has a breaking update, please have a look @qiweiii 
Ref: https://github.com/Magickbase/godwoken-explorer-ui/pull/776

**Comment by qiweiii** [comment]
upgrade wagmi PR: https://github.com/Magickbase/godwoken-explorer-ui/pull/789
